/**
 * Prop Odds API
 *  The Prop Odds API allows you to query player and game prop odds from different bookies. 
 *
 * The version of the OpenAPI document: 0.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FantasyBook from './FantasyBook';

/**
 * The FantasyBooks model module.
 * @module model/FantasyBooks
 * @version 0.9
 */
class FantasyBooks {
    /**
     * Constructs a new <code>FantasyBooks</code>.
     * @alias module:model/FantasyBooks
     * @param gameId {String} 
     * @param fantasyBooks {Array.<module:model/FantasyBook>} 
     */
    constructor(gameId, fantasyBooks) { 
        
        FantasyBooks.initialize(this, gameId, fantasyBooks);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, gameId, fantasyBooks) { 
        obj['game_id'] = gameId;
        obj['fantasy_books'] = fantasyBooks;
    }

    /**
     * Constructs a <code>FantasyBooks</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FantasyBooks} obj Optional instance to populate.
     * @return {module:model/FantasyBooks} The populated <code>FantasyBooks</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FantasyBooks();

            if (data.hasOwnProperty('game_id')) {
                obj['game_id'] = ApiClient.convertToType(data['game_id'], 'String');
            }
            if (data.hasOwnProperty('fantasy_books')) {
                obj['fantasy_books'] = ApiClient.convertToType(data['fantasy_books'], [FantasyBook]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>FantasyBooks</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>FantasyBooks</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of FantasyBooks.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['game_id'] && !(typeof data['game_id'] === 'string' || data['game_id'] instanceof String)) {
            throw new Error("Expected the field `game_id` to be a primitive type in the JSON string but got " + data['game_id']);
        }
        if (data['fantasy_books']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['fantasy_books'])) {
                throw new Error("Expected the field `fantasy_books` to be an array in the JSON data but got " + data['fantasy_books']);
            }
            // validate the optional field `fantasy_books` (array)
            for (const item of data['fantasy_books']) {
                FantasyBook.validateJSON(item);
            };
        }

        return true;
    }


}

FantasyBooks.RequiredProperties = ["game_id", "fantasy_books"];

/**
 * @member {String} game_id
 */
FantasyBooks.prototype['game_id'] = undefined;

/**
 * @member {Array.<module:model/FantasyBook>} fantasy_books
 */
FantasyBooks.prototype['fantasy_books'] = undefined;






export default FantasyBooks;

