/**
 * Prop Odds API
 *  The Prop Odds API allows you to query player and game prop odds from different bookies. 
 *
 * The version of the OpenAPI document: 0.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FantasyBookMarket from './FantasyBookMarket';

/**
 * The FantasyBookMultiMarket model module.
 * @module model/FantasyBookMultiMarket
 * @version 0.9
 */
class FantasyBookMultiMarket {
    /**
     * Constructs a new <code>FantasyBookMultiMarket</code>.
     * @alias module:model/FantasyBookMultiMarket
     * @param bookieKey {String} 
     * @param markets {Array.<module:model/FantasyBookMarket>} 
     */
    constructor(bookieKey, markets) { 
        
        FantasyBookMultiMarket.initialize(this, bookieKey, markets);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, bookieKey, markets) { 
        obj['bookie_key'] = bookieKey;
        obj['markets'] = markets;
    }

    /**
     * Constructs a <code>FantasyBookMultiMarket</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FantasyBookMultiMarket} obj Optional instance to populate.
     * @return {module:model/FantasyBookMultiMarket} The populated <code>FantasyBookMultiMarket</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FantasyBookMultiMarket();

            if (data.hasOwnProperty('bookie_key')) {
                obj['bookie_key'] = ApiClient.convertToType(data['bookie_key'], 'String');
            }
            if (data.hasOwnProperty('markets')) {
                obj['markets'] = ApiClient.convertToType(data['markets'], [FantasyBookMarket]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>FantasyBookMultiMarket</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>FantasyBookMultiMarket</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of FantasyBookMultiMarket.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['bookie_key'] && !(typeof data['bookie_key'] === 'string' || data['bookie_key'] instanceof String)) {
            throw new Error("Expected the field `bookie_key` to be a primitive type in the JSON string but got " + data['bookie_key']);
        }
        if (data['markets']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['markets'])) {
                throw new Error("Expected the field `markets` to be an array in the JSON data but got " + data['markets']);
            }
            // validate the optional field `markets` (array)
            for (const item of data['markets']) {
                FantasyBookMarket.validateJSON(item);
            };
        }

        return true;
    }


}

FantasyBookMultiMarket.RequiredProperties = ["bookie_key", "markets"];

/**
 * @member {String} bookie_key
 */
FantasyBookMultiMarket.prototype['bookie_key'] = undefined;

/**
 * @member {Array.<module:model/FantasyBookMarket>} markets
 */
FantasyBookMultiMarket.prototype['markets'] = undefined;






export default FantasyBookMultiMarket;

