/**
 * Prop Odds API
 *  The Prop Odds API allows you to query player and game prop odds from different bookies. 
 *
 * The version of the OpenAPI document: 0.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Game from './Game';

/**
 * The GameInfo model module.
 * @module model/GameInfo
 * @version 0.9
 */
class GameInfo {
    /**
     * Constructs a new <code>GameInfo</code>.
     * @alias module:model/GameInfo
     * @param league {String} 
     * @param game {module:model/Game} 
     */
    constructor(league, game) { 
        
        GameInfo.initialize(this, league, game);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, league, game) { 
        obj['league'] = league;
        obj['game'] = game;
    }

    /**
     * Constructs a <code>GameInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GameInfo} obj Optional instance to populate.
     * @return {module:model/GameInfo} The populated <code>GameInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GameInfo();

            if (data.hasOwnProperty('league')) {
                obj['league'] = ApiClient.convertToType(data['league'], 'String');
            }
            if (data.hasOwnProperty('game')) {
                obj['game'] = Game.constructFromObject(data['game']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GameInfo</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GameInfo</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of GameInfo.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['league'] && !(typeof data['league'] === 'string' || data['league'] instanceof String)) {
            throw new Error("Expected the field `league` to be a primitive type in the JSON string but got " + data['league']);
        }
        // validate the optional field `game`
        if (data['game']) { // data not null
          Game.validateJSON(data['game']);
        }

        return true;
    }


}

GameInfo.RequiredProperties = ["league", "game"];

/**
 * @member {String} league
 */
GameInfo.prototype['league'] = undefined;

/**
 * @member {module:model/Game} game
 */
GameInfo.prototype['game'] = undefined;






export default GameInfo;

