/**
 * Prop Odds API
 *  The Prop Odds API allows you to query player and game prop odds from different bookies. 
 *
 * The version of the OpenAPI document: 0.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Market from './Market';

/**
 * The Markets model module.
 * @module model/Markets
 * @version 0.9
 */
class Markets {
    /**
     * Constructs a new <code>Markets</code>.
     * @alias module:model/Markets
     * @param gameId {String} 
     * @param markets {Array.<module:model/Market>} 
     */
    constructor(gameId, markets) { 
        
        Markets.initialize(this, gameId, markets);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, gameId, markets) { 
        obj['game_id'] = gameId;
        obj['markets'] = markets;
    }

    /**
     * Constructs a <code>Markets</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Markets} obj Optional instance to populate.
     * @return {module:model/Markets} The populated <code>Markets</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Markets();

            if (data.hasOwnProperty('game_id')) {
                obj['game_id'] = ApiClient.convertToType(data['game_id'], 'String');
            }
            if (data.hasOwnProperty('markets')) {
                obj['markets'] = ApiClient.convertToType(data['markets'], [Market]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Markets</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Markets</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Markets.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['game_id'] && !(typeof data['game_id'] === 'string' || data['game_id'] instanceof String)) {
            throw new Error("Expected the field `game_id` to be a primitive type in the JSON string but got " + data['game_id']);
        }
        if (data['markets']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['markets'])) {
                throw new Error("Expected the field `markets` to be an array in the JSON data but got " + data['markets']);
            }
            // validate the optional field `markets` (array)
            for (const item of data['markets']) {
                Market.validateJSON(item);
            };
        }

        return true;
    }


}

Markets.RequiredProperties = ["game_id", "markets"];

/**
 * @member {String} game_id
 */
Markets.prototype['game_id'] = undefined;

/**
 * @member {Array.<module:model/Market>} markets
 */
Markets.prototype['markets'] = undefined;






export default Markets;

