const tintColorLight = '#2f95dc';
const tintColorDark = '#fff';

export default {
    light: {
        text: '#000',
        icon: '#000',
        tabBar: '#fff',
        background: '#fff',
        grayBackground: '#F5F5F5',
        grayBorder: '#EBEBEB',
        borderColor: "#000",
        tint: tintColorLight,
        tabIconDefault: '#ccc',
        tabIconSelected: tintColorLight,
        mainGreen: '#4AD346',
        mainBlue: '#1292CE',
        accentGreen: '#268023',
        accentBlue: '#0B5D83',
        greenText: '#25A74A',
        redText: '#ff5757',
        betMGM: '#d29f53',
        pointsbet: '#ed1b42',
        caesars: '#00322f',
        barstool: '#304977',
        yellowText: '#FEE12B',
    },
    dark: {
        text: '#fff',
        icon: '#fff',
        tabBar: '#121212',
        background: '#121212',
        grayBackground: '#313131',
        grayBorder: '#292929',
        borderColor: "#fff",
        tint: tintColorDark,
        tabIconDefault: '#ccc',
        tabIconSelected: tintColorDark,
        mainGreen: '#268023',
        mainBlue: '#0B5D83',
        accentGreen: '#4AD346',
        accentBlue: '#1292CE',
        greenText: '#36d363',
        redText: '#ff5757',
        betMGM: '#b1801e',
        pointsbet: '#bd0f2e',
        caesars: '#00322f',
        barstool: '#111a2b',
        yellowText: '#FCE205',
    },
};
