/**
 * Prop Odds API
 *  The Prop Odds API allows you to query player and game prop odds from different bookies. 
 *
 * OpenAPI spec version: 0.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Outcome } from '../models/Outcome';
import { HttpFile } from '../http/http';

export class BookMarket {
    'marketKey': string;
    'outcomes': Array<Outcome>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "marketKey",
            "baseName": "market_key",
            "type": "string",
            "format": ""
        },
        {
            "name": "outcomes",
            "baseName": "outcomes",
            "type": "Array<Outcome>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BookMarket.attributeTypeMap;
    }

    public constructor() {
    }
}

