/**
 * Prop Odds API
 *  The Prop Odds API allows you to query player and game prop odds from different bookies. 
 *
 * OpenAPI spec version: 0.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Line } from '../models/Line';
import { HttpFile } from '../http/http';

export class FantasyBookMarket {
    'marketKey': string;
    'lines': Array<Line>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "marketKey",
            "baseName": "market_key",
            "type": "string",
            "format": ""
        },
        {
            "name": "lines",
            "baseName": "lines",
            "type": "Array<Line>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FantasyBookMarket.attributeTypeMap;
    }

    public constructor() {
    }
}

