/**
 * Prop Odds API
 *  The Prop Odds API allows you to query player and game prop odds from different bookies. 
 *
 * OpenAPI spec version: 0.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FantasyBookMarket } from '../models/FantasyBookMarket';
import { HttpFile } from '../http/http';

export class FantasyBookMultiMarket {
    'bookieKey': string;
    'markets': Array<FantasyBookMarket>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "bookieKey",
            "baseName": "bookie_key",
            "type": "string",
            "format": ""
        },
        {
            "name": "markets",
            "baseName": "markets",
            "type": "Array<FantasyBookMarket>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FantasyBookMultiMarket.attributeTypeMap;
    }

    public constructor() {
    }
}

